version: "3"
services:
    client:
        image: node:16
        container_name: Care-Connections-Client
        working_dir: /home/node/app
        volumes:
            - ./client/:/home/node/app
        ports:
            - ${CLIENT_PORT}:3000
        command: bash -c "yarn install && yarn dev"
        depends_on:
            - "mongodb"

    api:
        image: node:16
        container_name: Care-Connections-API
        working_dir: /home/node/app
        volumes:
            - ./api/:/home/node/app
        ports:
            - ${API_PORT}:3001
        command: bash -c "yarn install && yarn dev"
        depends_on:
            - "mongodb"

    mongodb:
        container_name: MongoDB
        image: mongo
        ports:
            - 27017:27017
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=admin
            - MONGO_INITDB_DATABASE=${DATABASE_NAME}
        volumes:
            - D:\Projects\Programmas\CareKickoff\init.js:/docker-entrypoint-initdb.d/init.js:ro
            - D:\Projects\Programmas\CareKickoff\Data:/init/
            - mongo-data:/data/db
        command: [--auth]
        restart: on-failure

    mongo-express:
        container_name: Mongo-Express
        image: mongo-express
        ports:
            - ${MONGO_EXPRESS_PORT}:8081
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
            - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
            - ME_CONFIG_BASICAUTH_USERNAME=admin
            - ME_CONFIG_BASICAUTH_PASSWORD=admin
            - ME_CONFIG_MONGODB_SERVER=mongodb
        restart: always
        depends_on:
            - "mongodb"

volumes:
    mongo-data:
        driver: local
