version: "3"
services:
    client:
        image: node:16
        container_name: Care-Connections-Client
        working_dir: /home/node/app
        volumes:
            - ./client/:/home/node/app
        ports:
            - 3000:3000
        command: yarn dev
        depends_on:
            - "mongodb"

    api:
        image: node:16
        container_name: Care-Connections-Server
        working_dir: /home/node/app
        volumes:
            - ./api/:/home/node/app
        ports:
            - 3001:3001
        command: node index.js
        depends_on:
            - "mongodb"

    mongodb:
        container_name: MongoDB
        image: mongo
        ports:
            - 27017:27017
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=admin
        volumes:
            - mongo-data:/data/db
        restart: on-failure

    mongo-express:
        container_name: Mongo-Express
        image: mongo-express
        ports:
            - 3002:8081
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
            - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
            - ME_CONFIG_BASICAUTH_USERNAME=admin
            - ME_CONFIG_BASICAUTH_PASSWORD=admin
            - ME_CONFIG_MONGODB_SERVER=mongodb
        restart: on-failure
        depends_on:
            - "mongodb"

volumes:
    mongo-data:
        driver: local
